steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - -t 
      - gcr.io/gcer-public/googleauthr:$SHORT_SHA 
      - -t 
      - gcr.io/gcer-public/googleauthr:$BRANCH_NAME 
      - '.'
  - name: gcr.io/cloud-builders/docker
    args: 
      - push 
      - gcr.io/gcer-public/googleauthr