---
title: "Data API for Google Analytics 4 (App+Web)"
---

The Data API and Google Analytics Admin API are used with the Google Analytics 4 properties, the newest version of Google Analytics and evolution from Universal Analytics.  

## Features

* Only API to fetch data from Google Analytics 4 properties
* Ability to create your own custom metrics and dimensions
* Can send in up to 4 date ranges at once
* Easier integration with the real-time API

## Meta data

Universal metadata for what you can query via the Data API can be found by specifying that API in the `ga_meta()` function:

```r
metadata <- ga_meta(version = "data")
```

You may have custom dimensions and metrics setup for your web property - to get a list of those specify the web property in the meta data call:

```r
# Google Analytics 4 metadata for a particular Web Property
ga_meta("data", propertyId = 206670707)
```

## Fetching data

The primary data fetching function is `google_analytics_aw()` (name may change in future)

You need your propertyId to query data, and then at least a metric and date range:

```r
# replace with your propertyId
my_property_id <- 206670707
basic <- google_analytics_aw(
  my_property_id,
  metrics = c("activeUsers","sessions"),
  date_range = c("2020-03-31", "2020-04-27")
  )
```

Dimensions can be added to split out your results:

```r
# split out metrics by the dimensions specified
dimensions <- google_analytics_aw(
    my_property_id,
    metrics = c("activeUsers","sessions"),
    dimensions = c("date","city","dayOfWeek"),
    date_range = c("2020-03-31", "2020-04-27")
)
```

By default the API returns 100 results.  Add the `limit` parameter to change the number of results returned.  To get all results, use -1

```r
only_10 <- google_analytics_aw(
    my_property_id,
    metrics = c("activeUsers","sessions"),
    dimensions = c("date","city","dayOfWeek"),
    date_range = c("2020-03-31", "2020-04-27"),
    limit = 10
)

all_results <- google_analytics_aw(
    my_property_id,
    metrics = c("activeUsers","sessions"),
    dimensions = c("date","city","dayOfWeek"),
    date_range = c("2020-03-31", "2020-04-27"),
    limit = -1
)
```

## Real Time Data

Real-time data can be fetched with the same function as the regular Data API, but it is calling another endpoint.  Add the `realtime=TRUE` argument to the function.  

A limited subset of [dimensions and metrics are available in the real-time API](https://developers.google.com/analytics/devguides/reporting/data/v1/realtime-api-schema).  Date ranges are ignored.

```r
# run a real-time report 
realtime <- google_analytics_aw(
  206670707,
  metrics = "activeUsers",
  dimensions = "city",
  dimensionFilter = ga_aw_filter("city", "Copenhagen", "EXACT"),
  limit = 100,
  realtime = TRUE)
```