#' Returns multiple reports in a batch. All reports must be for the sameEntity.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/analytics/trusted-testing/analytics-data/}{Google Documentation}
#'
#' @details
#'
#' @param BatchRunReportsRequest The \link{BatchRunReportsRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family BatchRunReportsRequest functions
#' @export
batchRunReports <- function(BatchRunReportsRequest) {
  url <- "https://analyticsdata.googleapis.com/v1alpha:batchRunReports"
  # analyticsdata.batchRunReports
  f <- gar_api_generator(url, "POST", 
                         data_parse_function = parse_batchrunreports)
  
  stopifnot(inherits(BatchRunReportsRequest, "gar_BatchRunReportsRequest"))
  o <- f(the_body = BatchRunReportsRequest)
  
  o
}

get_value <- function(x, 
                      type = c("dimensionValues", "metricValues")){
  type <- match.arg(type)
  lapply(x[[type]], function(y) y[["value"]])
} 

parse_batchrunreports <- function(x){
  o <- x$reports
  lapply(o$rows, function(y){
    cbind(get_value(y, "dimensionValues"), 
          get_value(y, "metricValues"))
  })
}



#' BatchRunReportsRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The batch request containing multiple report requests.
#'
#' @param entity A property whose events are tracked
#' @param requests Individual requests
#'
#' @return BatchRunReportsRequest object
#'
#' @family BatchRunReportsRequest functions
#' @export
BatchRunReportsRequest <- function(entity = NULL, requests = NULL){
  
  structure(list(entity = entity, 
                 requests = rmNullObs(requests)), 
            class = c("gar_BatchRunReportsRequest","list"))
}


#' RunReportRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request to generate a report.
#'
#' @param entity A property whose events are tracked
#' @param metrics The metrics requested and displayed
#' @param currencyCode A currency code in ISO4217 format, such as 'AED', 'USD', 'JPY'
#' @param orderBys Specifies how rows are ordered in the response
#' @param metricFilter The filter clause of metrics
#' @param cohortSpec Cohort group associated with this request
#' @param metricAggregations Aggregation of metrics
#' @param dimensions The dimensions requested and displayed
#' @param dateRanges Date ranges of data to read
#' @param keepEmptyRows If false, rows with metrics being 0 will not be returned
#' @param dimensionFilter The filter clause of dimensions
#' @param limit The number of rows to return
#' @param offset The row count of the start row
#' @param returnPropertyQuota Toggles whether to return the current state of this Analytics Property's
#'
#' @return RunReportRequest object
#'
#' @family RunReportRequest functions
#' @export
RunReportRequest <- function(entity = NULL, 
                             metrics = NULL, 
                             currencyCode = NULL,
                             orderBys = NULL, 
                             metricFilter = NULL, 
                             cohortSpec = NULL, 
                             metricAggregations = NULL,
                             dimensions = NULL, 
                             dateRanges = NULL, 
                             keepEmptyRows = NULL, 
                             dimensionFilter = NULL,
                             limit = NULL, 
                             offset = NULL, 
                             returnPropertyQuota = NULL){
  
  structure(list(entity = entity, 
                 metrics = metrics, 
                 currencyCode = currencyCode,
                 orderBys = orderBys, 
                 metricFilter = metricFilter, 
                 cohortSpec = cohortSpec,
                 metricAggregations = metricAggregations, 
                 dimensions = dimensions, 
                 dateRanges = dateRanges,
                 keepEmptyRows = keepEmptyRows, 
                 dimensionFilter = dimensionFilter, 
                 limit = limit,
                 offset = offset, 
                 returnPropertyQuota = returnPropertyQuota), 
            class = c("gar_RunReportRequest", "list"))
}

#' Entity Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The unique identifier of the property whose events are tracked.
#'
#' @param propertyId A Google Analytics App + Web property id
#'
#' @return Entity object
#'
#' @family Entity functions
#' @export
Entity <- function(propertyId = NULL) {
  structure(list(propertyId = propertyId),
            class = c("gar_Entity", "list"))
}

#' Metric Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The quantitative measurements of a report. For example, the metric eventCount is the total number of events. Requests are allowed up to 10 metrics.
#'
#' @param expression A mathematical expression for derived metrics
#' @param invisible Indicates if a metric is invisible
#' @param name The name of the metric
#'
#' @return Metric object
#'
#' @family Metric functions
#' @export
Metric <- function(expression = NULL,
                   invisible = NULL,
                   name = NULL) {
  structure(list(expression = expression,
                 invisible = invisible,
                 name = name),
            class = c("gar_Metric", "list"))
}

#' DimensionExpression Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Used to express a dimension which is the result of a formula of multipledimensions. Example usages:1) lower_case(dimension)2) concatenate(dimension1, symbol, dimension2).
#'
#' @param lowerCase Used to convert a dimension value to lower case
#' @param concatenate Used to combine dimension values to a single dimension
#' @param upperCase Used to convert a dimension value to upper case
#'
#' @return DimensionExpression object
#'
#' @family DimensionExpression functions
#' @export
DimensionExpression <- function(lowerCase = NULL, 
                                concatenate = NULL, 
                                upperCase = NULL) {
  structure(list(lowerCase = lowerCase, concatenate = concatenate, upperCase = upperCase),
            class = c("gar_DimensionExpression", "list"))
}

#' Dimension Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Dimensions are attributes of your data. For example, the dimension City indicates the city, for example, 'Paris' or 'New York', from which an event originates. Requests are allowed up to 8 dimensions.
#'
#' @param name The name of the dimension
#' @param dimensionExpression One dimension can be the result of an expression of multiple dimensions
#'
#' @return Dimension object
#'
#' @family Dimension functions
#' @export
Dimension <- function(name = NULL, dimensionExpression = NULL) {
  structure(list(name = name, 
                 dimensionExpression = dimensionExpression), 
            class = c("gar_Dimension","list"))
}

