#' Returns multiple reports in a batch. All reports must be for the sameEntity.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/analytics/trusted-testing/analytics-data/}{Google Documentation}
#'
#' @details
#'
#' @param BatchRunReportsRequest The \link{BatchRunReportsRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family BatchRunReportsRequest functions
#' @export
google_analytics_aw <- function(propertyId,
                                metrics,
                                date_range,
                                dimensions,
                                dimensionFilter = NULL,
                                metricFilter = NULL,
                                limit = 10) {
  url <- "https://analyticsdata.googleapis.com/v1alpha:batchRunReports"
  
  brrr <- BatchRunReportsRequest(
    entity = list(propertyId = as.character(propertyId)),
    requests = list(
      RunReportRequest(
        metrics = lapply(metrics, function(x) Metric(name = x)),
        dimensions = lapply(dimensions, function(x) Dimension(name = x)),
        dateRanges = date_ga4(date_range),
        limit = limit,
        keepEmptyRows = TRUE,
        returnPropertyQuota = TRUE
      )
    )
  )
  
  parse_batchrunreports <- function(x){
    o <- x$reports

    the_data <- lapply(o$rows, function(x){
      o <- cbind(get_value_cols(x, type = "dimensionValues"),
                 get_value_cols(x, type = "metricValues"))
      setNames(o, c(dimensions, metrics))
    })
    
    res <- Reduce(rbind, the_data)
    attr(res, "propertyQuota") <- o$propertyQuota
    attr(res, "metadata") <- if(ncol(o$metadata) > 0) o$metadata else NULL
    
    res
  }
  
  
  # analyticsdata.batchRunReports
  f <- gar_api_generator(url, "POST", 
                         data_parse_function = parse_batchrunreports)
  
  stopifnot(inherits(brrr, "gar_BatchRunReportsRequest"))
  o <- f(the_body = brrr)
  
  o
}

#' @noRd
#' @importFrom tibble as_tibble
get_value_cols <- function(x, 
                      type = c("dimensionValues", "metricValues")){
  type <- match.arg(type)
  as_tibble(
    do.call(rbind, lapply(x[[type]], function(y) y[["value"]])),
    .name_repair = "minimal")
} 

