#' Authenticate with Google Analytics OAuth2
#'
#' A wrapper for \link[googleAuthR]{gar_auth} and \link[googleAuthR]{gar_auth_service}
#'
#' @param new_user If TRUE, reauthenticate via Google login screen
#' 
#' @details
#' 
#' Run this function first time to authenticate with Google in your browser.  
#' 
#' After initial authentication, a \code{.httr-oauth} will be saved to your working directory, where your authentication details are kept.  Keep this file safe.
#' 
#' If you want to reauthenticate, delete this file from your directory or run \code{ga_auth(new_user = TRUE)}
#' 
#' @section Auto-authentication:
#' 
#' You can choose to auto-authenticate by moving your \code{.httr-oauth} or by 
#'   creating a Google OAuth service account JSON file.
#' 
#' Specify an environment variable in R via a \code{.Renviron} file or using \link{Sys.setenv} which point to the file location of your chosen authentication file.
#' 
#' Once you have set the environment variable \code{GA_AUTH_FILE} to a valid file location,
#'   the function will look there for authentication details upon loading the library meaning 
#'   you will not need to call \code{ga_auth()} yourself as you would normally.
#' 
#' An example \code{.Renviron} file is below:
#' 
#' \code{GA_AUTH_FILE = "/Users/bob/auth/googleAnalyticsR.httr-oauth"}
#'
#' \code{GA_AUTH_FILE} can be either a token generated by \link[googleAuthR]{gar_auth} or
#'   service account JSON ending with file extension \code{.json}
#'   
#' If you use the service account JSON, you will need to add the service account email 
#'   to your Google Analytics users to see data e.g. \code{xxxx@yyyyyy.iam.gserviceaccount.com}
#'
#' @return Invisibly, the token that has been saved to the session
#' @import googleAuthR
#' @importFrom tools file_ext
#' @export
ga_auth <- function(new_user = FALSE){
  
  needed <- c("https://www.googleapis.com/auth/analytics", 
              "https://www.googleapis.com/auth/analytics.readonly",
              "https://www.googleapis.com/auth/analytics.manage.users.readonly",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.manage.users",
              "https://www.googleapis.com/auth/analytics.provision"	)
  
  if(!any(getOption("googleAuthR.scopes.selected") %in% needed)){
    stop("Cannot authenticate - getOption('googleAuthR.scopes.selected') needs to include at least https://www.googleapis.com/auth/analytics.readonly")
  }
  
  auth_file <- Sys.getenv("GA_AUTH_FILE")
  
  if(auth_file == ""){
    ## normal auth looking for .httr-oauth in working folder or new user
    out <- googleAuthR::gar_auth(new_user = new_user)
  } else {
    ## auth_file specified in GCS_AUTH_FILE
    if(file.exists(auth_file)){
      ## Service JSON file
      if(tools::file_ext(auth_file) == "json"){
        out <- googleAuthR::gar_auth_service(auth_file)
      } else {
        ## .httr-oauth file
        token <- readRDS(auth_file)
        out <- googleAuthR::gar_auth(token = token[[1]])
      }
    } else {
      ## auth_file specified but not present
      stop("GA_AUTH_FILE specified in environment variables but file not found.")
    }
  }
  

  out <- googleAuthR::gar_auth(new_user = new_user)
  message("Authenticated")
  out
}